### ISSUE TITLE
Make tree-view-git-status work together with the Nuclide editor

### ISSUE THREAD

**Issue by subesokun** [subesokun/atom-tree-view-git-status#16]
- Check for compatibility issues with the `nuclide-tree-view`
- Setup tests

**Comment by subesokun** [comment]
Use `atom.packages.onDidActivateInitialPackages` event, see [this topic](https://discuss.atom.io/t/is-there-a-way-to-load-the-editors-default-tree-view/22710/2)

**Comment by alvaropinot** [comment]
Related with https://github.com/facebook/nuclide/issues/1205
