### ISSUE TITLE
Coloring in tree view doesn't work

### ISSUE THREAD

**Issue by victorleblais** [subesokun/atom-tree-view-git-status#17]
Hi,

I've installed this plugin and this doesn't seem to work for me: I can't see any coloring showing that I have modified files in my local workspace.

Here is a screenshot using a custom theme (Atom Material):
![Colors not showing in tree view, with Atom Material theme](http://i.imgur.com/rjA8DTd.png)

And here is one using the default One Dark theme, with all my other plugins disabled:
![Colors not showing in tree view, with One Dark theme](http://i.imgur.com/ao3C8fk.png)

Again, One Dark theme and all my plugins disabled, except project-view and tree-view-git-status:
![Colors not showing in tree view, with One Dark theme and all other plugins disabled](http://i.imgur.com/1li7iJv.png)

I'm using Atom 1.2.4 on OSX 10.11.1.

I can provide more informations if needed.

**Comment by subesokun** [comment]
Hi @victorleblais! Actually the tree-view package colors only the root folder of your project and not the other sub-folder or files as this is done by the atom tree-view itself. If it's not working well there might be something off with your Atom installation itself. Sometimes the `git-utils` of Atom behaves strange... not sure how I can help you in this case. Maybe you should report this issue directly in the Atom discourse forum.

**Comment by victorleblais** [comment]
You are indeed correct. My bad.

The cause of this issue is due to a negation in my gitignore not being correctly interpreted. There's an issue in tree-view about that problem here: https://github.com/atom/tree-view/issues/196

I'm closing this issue since it is not related to atom-tree-view-git-status.
