### ISSUE TITLE
Add support for worktrees

### ISSUE THREAD

**Issue by karrots** [subesokun/atom-tree-view-git-status#19]
When a work tree is added to the project it doesn't show status.

**Comment by subesokun** [comment]
Hi @karrots, do you mean that in case of adding a new "Project Folder" while Atom is running then the Git status is not shown correctly? Or generally no Git status is shown in the tree view? Could you tell me which version of Atom you're using and which version of tree-view-git-status? A screenshot would be also great.

**Comment by karrots** [comment]
No status is shown in the tree view for the work tree folder only. The master branch shows status. It looks as though it's just a standard folder.

atom-tree-view-git-status  0.2.2
Atom version 1.4.0

https://goo.gl/photos/QHS6HVhZNpTD15Nx7

**Comment by subesokun** [comment]
Hi @karrots, sorry for the delay. Actually for me everything looks ok. For your first project folder the git status gets correctly displayed and your second project folder seems like to have no Git folder (.git is missing) hence Atom will not recognize it as a Git repository. Are you sure that this `RaspberryPi-Gateway-imagebuilder` folder is under version control?

**Comment by karrots** [comment]
Yes it is a Git [worktree](https://git-scm.com/docs/git-worktree) so there is no .git folder just a .git file reference to the main repository. All of the version control information is stored centrally in the main repo.

**Comment by subesokun** [comment]
@karrots Mhh I see. Then it seems that Atom itself, to be more precise the [git-utils](https://github.com/atom/git-utils), has some issues at recognizing such Git worktree :( The tree-view-git-status package just reads out the SCM informations received from Atom so there's not so much I can do at the moment for you. Please feel free to create an issue on the git-utils repo, or open a discussion on atom.io and I'd be great if you could post here a link then.

**Comment by subesokun** [comment]
Closing this issue as it's Atom related and thanks for reporting the issue in the `git-utils` repo :+1:
