### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by subinvarghesein** [subesokun/atom-tree-view-git-status#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.179.0
**System**: linux 3.13.0-53-generic
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/svarghese/.atom/packages/tree-view-git-status/lib/main.coffee:177

TypeError: Cannot read property 'length' of undefined
  at Object.module.exports.TreeViewGitStatus.updateRoots (/home/svarghese/.atom/packages/tree-view-git-status/lib/main.coffee:177:7)
  at /home/svarghese/.atom/packages/tree-view-git-status/lib/main.coffee:139:10
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.setPaths (/usr/share/atom/resources/app/src/project.js:217:27)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:38:25)
  at EventEmitter.emit (events.js:119:17)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
autocomplete-plus, v2.2.0
emmet, v2.3.10
file-icons, v1.5.1
jshint, v1.3.1
minimap, v4.3.1
project-manager, v1.15.8
spacegray-dark-ui, v0.12.0
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by subesokun** [comment]
Thanks for reporting the issue :+1:

I see that you're using a quite old version of Atom released on 11 Feb and since then the Atom API has changed quite a bit. Is it possible for you to update to a newer version and tell me if you still see the same error there?

**Comment by subesokun** [comment]
As I'm not planning to support such old versions of Atom it'd be great if you could update your Atom and see if you've still the same issue there. If so, please ping me here and attach the new error trace. Closing this issue for now.
