### ISSUE TITLE
Changed vs. New unstaged

### ISSUE THREAD

**Issue by hendricha** [subesokun/atom-tree-view-git-status#20]
Tree view git status colors all repos that contain any new, untracked files orange. Within the repo the gitutils coloring colors these as green. Could you match this behaviour too? (If there are only untracked files, mark repo green instead of orange.)

(Sadly my current workflow has multiple repos that have multiple uncommited .styl files, because I'm just locally compiling them to .css, until we have a company policy on how to deal with .styl files. XD)

**Comment by subesokun** [comment]
Hi @hendricha, yes I think that should be possible. I've noticed this already too but it was so far a minor missing feature for me. Maybe I can land a new release this weekend containing this feature :)

**Comment by hendricha** [comment]
Cool, thanks.
