### ISSUE TITLE
Push pending?

### ISSUE THREAD

**Issue by nerdpad** [subesokun/atom-tree-view-git-status#24]
Is it possible to show indicator when there are unpushed commits in a repo?

I have commits in my branch which are not pushed yet, so the remote branch is behind my local branch. Is there any way to indicate this?

**Comment by subesokun** [comment]
Hi @NerdPad, unpushed commits are indicated by an⬆️arrow and if your branch is behind the remote branch this is indicated via an ⬇️ arrow for the current active branch. The numbers next to the arrows are showing how many commits you're ahead/behind, see https://github.com/subesokun/atom-tree-view-git-status/blob/master/screenshot.png?raw=true 

Does this answer your question?

**Comment by nerdpad** [comment]
@subesokun I have all the options selected, but I do not see any arrows, like the one in the screenshot.

How can I help?

**Comment by nerdpad** [comment]
It's working. So closing the issue.
