### ISSUE TITLE
Branch isn't visible in tree in Atom 1.8.0

### ISSUE THREAD

**Issue by wolfadex** [subesokun/atom-tree-view-git-status#25]
The name of the branch isn't visible in the tree.

Atom: v1.8.0
OS: Ubuntu 14.04

**Comment by subesokun** [comment]
Hi @wolfadex, thanks for taking your time to report this issue. I'm currently working on that issue since Atom introduced in a minor release a breaking change... seems like they aren't bothering so much about semantic versioning :p A new release will be available by the end of this week.

**Comment by seanbuscay** [comment]
Thank you for such a quick fix. Your package is very helpful and I'll be glad to have it back.

**Comment by subesokun** [comment]
@seanbuscay, sure you're welcome :) v1.0.0 has been released so you can give it a try 😃
