### ISSUE TITLE
updated to latest

### ISSUE THREAD

**Issue by jontie-vWork** [subesokun/atom-tree-view-git-status#31]
I am using osx and the package is not working.

**Comment by subesokun** [comment]
Hi @jontie-vWork, do you've some more information for me? Atom version, package version, any error messages or screenshots, ... I've tested the latest v1.0.2 release also on OSX and it worked for me.

**Comment by chance-focalcast** [comment]
I'm having the same issue.

I'm running on Atom 1.9, package 1.0.2, and I'm on OSX.

![image](https://cloud.githubusercontent.com/assets/19413577/17334670/b5846f74-589c-11e6-98c6-888607d7b0a8.png)

![image](https://cloud.githubusercontent.com/assets/19413577/17334216/0554e26a-589b-11e6-99a9-898a7bdf311c.png)

No error messages are appearing.

Only started happening yesterday after closing and reopening Atom.

Sorry I don't have anything else for you. Let me know if there's anything else I can do to help.

**Comment by subesokun** [comment]
@chance-focalcast, the package is currently not working together with the
latest Atom 1.9 as some API has been deprecated but a patch will be soon
available.

chance-focalcast notifications@github.com schrieb am Di., 2. Aug. 2016,
17:22:

**Comment by chance-focalcast** [comment]
Fantastic! Thanks for the notice.

**Comment by joshuatoenyes** [comment]
Same issue here (OS X on Atom 1.9.2). Thanks @subesokun!
