### ISSUE TITLE
Doesn't work in a symlinked directory

### ISSUE THREAD

**Issue by ayberkozgur** [subesokun/atom-tree-view-git-status#33]
Nothing is displayed next to the project name when the project directory is symlinked to somewhere else.

**Comment by subesokun** [comment]
Hi @ayberkozgur, in case the directory is symlinked do you see any Git status in lower right corner of Atom itself? If Atom doesn't report the directory as a Git repository then this package won't show also any information. If Atom also doesn't show any Git status you might need to file an issue directly to Atom.

**Comment by ayberkozgur** [comment]
@subesokun you're right, I didn't notice that. I'll move this to atom. Thanks.
