### ISSUE TITLE
Branch info invisible when tree is in focus

### ISSUE THREAD

**Issue by ProLoser** [subesokun/atom-tree-view-git-status#37]
This is when the tree panel is not in focus:

![image](https://cloud.githubusercontent.com/assets/67395/19401577/e69b2a32-9210-11e6-8efb-47dfc0d6b391.png)

This is what I see when it is focused:

![image](https://cloud.githubusercontent.com/assets/67395/19401572/d9422ea8-9210-11e6-8fb2-6339f9ae4c72.png)

**Comment by subesokun** [comment]
Hi @ProLoser, could you tell me which theme you're using? Most likely your currently used theme has a too restrictive CSS query for styling the project name.

**Comment by ProLoser** [comment]
![image](https://cloud.githubusercontent.com/assets/67395/19413649/27522472-92e8-11e6-9ed8-28431dbb8820.png)

**Comment by pingshunhuangalex** [comment]
Same problem with Material Theme, but I guess there is probably nothing you can do here. The author of this theme seems to be inactive for a while now...

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
