### ISSUE TITLE
This wonderful package stopped working for me

### ISSUE THREAD

**Issue by rcrooks** [subesokun/atom-tree-view-git-status#39]
I think just today, though not sure. Thought it might be related to the UI theme, but tried others with no luck. Haven't seen any errors, just stopped working.

**Comment by subesokun** [comment]
Hi @rcrooks, sorry for the delayed answer. Could you tell me which version of Atom you're using and which UI theme? Does switching back to a standard UI theme help?

**Comment by rcrooks** [comment]
Hi @subesokun - I've tried it both on the current released and latest beta versions of Atom, and switching UI themes makes no difference. If you haven't had other reports of this, I'm guessing it's a conflict with some other package. Guess there's nothing to do but disable them one by one and try to find the culprit (sigh:)

**Comment by ctcpip** [comment]
+1 on fresh install of Atom and this package on OSX Sierra

**Comment by subesokun** [comment]
Do you see any branch information when opening a version controlled file with Atom on the bottom right pane of the editor?

**Comment by rcrooks** [comment]
Sorry, thought I'd responded earlier - I figured out the issue - I'd opened a site folder that had some of my git project symlinked into it. When I open the original git working copy folders, all is well. Unless you feel like trying to tackle the symlink use case, feel free to close this.

**Comment by subesokun** [comment]
Ah right, Atom doesn't recognise symlinked Git repositories so there is actually nothing I can do about :( But thanks for the heads-up!

**Comment by ctcpip** [comment]
Figured out my issue as well - I was adding a root folder which _contained_ folders under SCM.  I guess the git information is only picked up if the project directory added is the actual git repo directory.

**Comment by subesokun** [comment]
@ctcpip glad to hear that is working for you again. Mhhh thought this feature used to work before. I'll look into it but closing this issue for now.
