### ISSUE TITLE
Projects with multiple git repositories

### ISSUE THREAD

**Issue by sohocoke** [subesokun/atom-tree-view-git-status#4]
I invariably end up loading a directory containing multiple git repositories as an Atom project, where the otherwise awesome git status is not displayed in the tree view.

Is it feasible to apply the detection on any directory in the project that has a `.git/`subdirectory, rather than the project root?

**Comment by subesokun** [comment]
Hi @sohocoke, do you mean a tree structure like the following?

```
projectfolder
  |_ somefolder [show here git status]
           |_ .git
           |_ ...
```

Sadly this won't be possible at the moment as `atom.project.getRepositories()` returns only repositories that are project folders. As Atom supports multiple project folders I'd recommend adding each of your repositories as separate project folder (`File > Add Project Folder...`).

**Comment by subesokun** [comment]
@sohocoke As this feature proposed by you is currently not feasible with Atom I'm closing this issue for now. Feel free to ask more questions if you've any.

**Comment by bazzilic** [comment]
Is this still not possible to do with Atom?

**Comment by bazzilic** [comment]
@subesokun hey, any updates on this?

**Comment by subesokun** [comment]
Sorry I haven't followed the latest Atom release notes but I guess it's still not possible. You'd need to get in direct contact with the Atom developers to get more information.
