### ISSUE TITLE
Git Status Label is not showing any more

### ISSUE THREAD

**Issue by pingshunhuangalex** [subesokun/atom-tree-view-git-status#44]
I have never had any problem with this plugin, but out of the blue, it just stops showing the branch status label next to the repository name...
![image](https://cloud.githubusercontent.com/assets/17170199/22576827/24f944fe-ea12-11e6-9fb2-5fed8486d855.png)

The repository is still recognised and can be manipulated without any problems (colouring based on git status, switching branches, commit, push, etc.), but the label just never shows up again. I didn't recall doing anything other than doing a `pull -rebase` if anything.

I then tried to `git clone` the entire repository to start fresh, but no luck. Now I even clean re-install the entire atom, still not working. I tried both Atom stable and Atom beta, and currently stay on beta version. It's driving me crazy... Please help me. Thanks.

**Comment by subesokun** [comment]
Hi @pingshunhuangalex, sorry to hear that you've issues. Could you give me some more details like which Atom version are you using, which OS and which Atom theme?

Also if you open a file of your `SNACRF` project, do you see any branch information like `master` on the bottom right of your editor?

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 

Thanks for the reply.

I'm using Win 10 64-bit. The problem first popped up in the latest stable version (`1.13.1`), then I switched to the latest beta version (`1.14.0 beta 4`), the issue remains. Both of the version I tested on clean installation and wipe out everything including cache.

The theme I'm using is `material-ui` and `material-syntax-dark`. I did try to switch it back to `atom-one-dark`, and the problem remains, not to mention it once worked on `material-ui theme` just fine.

When opening any file in the project (after clean installation), I can clearly see all the branches and can switch among them without any problem. Atom's gutter and file name colouring are also working. Features I got from `git-plus` works as well. As a matter of fact, `git status label` is the only one thing that breaks.

Thanks.

**Comment by pingshunhuangalex** [comment]
@subesokun Any luck on finding what could possibly go wrong here? Thanks.

**Comment by subesokun** [comment]
@pingshunhuangalex I was testing it now on Window, Linux and macOS with the latest version of Atom had no issues so far. I had only a little trouble with the beta version of Atom. But after reinstalling the `tree-view-git-status` package and uninstalling some other tree view related packages it was working again. Probably one of the other packages messed up my Atom. Not sure if the reinstallation of the `tree-view-git-status` package was necessary. Could you double check if you've maybe installed some other package that breaks the tree view? Also I've tried your mentioned theme setting and it still worked for me.

You seem to be familiar with Atom debugging, could you open the Developer Tools and check if you can see there some tree view related errors? Also the CI pipeline looks fine so it's hard to tell what's going wrong in your case :(

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 
I'm glad you mentioned all the details including the trivial above. After checking the Developer Tools (no error found), I just went away and reinstall `tree-view-git-status` and it just works like a charm now...

I did clear everything and now I'm even using a 64-bit atom beta which should start everything from scratches, but obviously there is probably still something hidden. I did pull all my settings and packages from `sync-settings` when I did the reinstallation, not sure if that's the reason...

Anyway all good now. Thank you so much. I guess "always check if the computer is plugged before redoing your OS" does have its point :)

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 
Sorry, I jump to the conclusion there.
What really happened is after I restart Atom, the git status label goes away again. Then I found out there is no `tree-view-git-status` options in the command menu (`ctrl+shift+p`) at all when it first starts. I have to go into the package to disable then re-enable the package for everything to work. And when I restart atom again, I'll lose it again.

Therefore, the problem comes to `tree-view-git-status` won't load itself at Atom startup. However, when I checked `timecop`, `tree-view-git-status` is actually in the package activation list. So I'm really confused right now. Hope that provides some extra information on the issue. Thanks.

**Comment by subesokun** [comment]
Thanks for your investigation! This sounds to me like in your case `atom.packages.onDidActivateInitialPackages` never gets fired 😕 https://github.com/subesokun/atom-tree-view-git-status/blob/master/lib/main.coffee#L46 could you add some `console.log` to see if this function gets called in your case when restarting the editor?

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 
Thanks for the instructions. Hope the screenshot below helps. Thanks.
![image](https://cloud.githubusercontent.com/assets/17170199/22761842/a60c6f6a-eeb0-11e6-9483-e7485c6e426c.png)

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 
Finally, I found the reason. As you can see from the screenshot above, it's the `autocomplete-python` package I'm using that's blocking your package from starting up because it can't cope with space in windows user directory. Issue reported here: https://github.com/autocomplete-python/autocomplete-python/issues/282

However having said that, `tree-view-git-status` is the only package that gets blocked somehow. All my other packages are all loading just fine. Therefore, I'm hoping if there is anything you can do to bypass this situation here, just like the other packages. Thanks.

P.S. Your other package `project-view` is suffering from the same issue here. If you find a solution, I assume it's transferrable in this case.

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 
I found a way to turn off the kite engine in `autocomplete-python`, so nothing will block `tree-view-git-status` at startup. If you can still find a workaround, that'll be a plus. However, if you struggle, maybe just leave it as it is as it's been taken care of. Thanks.

**Comment by subesokun** [comment]
Sorry for the delay and thanks a lot for you investigations! I've released now a new version that comes with a workaround for the issue that one ore more packages are failing to activate. Could you test if that solves also your issue with `autocomplete-python`?

**Comment by pingshunhuangalex** [comment]
Hi @subesokun 
Thanks for getting back to me. I tried to turn the `kite-engine` back on in `autocomplete-python`, but I think the guys there also took precaution about this, i.e. the option won't be turned on if it's not supported as it's now a mac-only feature.

Therefore, long story short, there is nothing I can test on as all packages are loading just fine, but I believe the extra second should make the start-up conflict go away if there will be any later.

Thanks for being so responsive, and keep up the good work :)
