### ISSUE TITLE
sometimes tree view status display abnormal

### ISSUE THREAD

**Issue by mathcad** [subesokun/atom-tree-view-git-status#46]
~~sometimes, there's no modification, but when open the file, it marked as modified in tree view. status bar says all line were replaced.~~
~~use 'git status' command could comfirm there's nothing changed in this file.~~

Ohh....it's not this pluggin's problem....sorry

**Comment by subesokun** [comment]
Hehe yes just wanted to say that you've to file your issue here https://github.com/atom/git-utils
Closing this one :)
