### ISSUE TITLE
Not Working w/ Symbolic Links

### ISSUE THREAD

**Issue by vastsoun** [subesokun/atom-tree-view-git-status#49]
Hi,

Instead of tediously adding each repo directory to the project, I use a "src" dir where I place symbolic links to all repositories. In this case, atom-tree-view-git-status does not show the status any more. Do I have to configure something to get this to work or is this missing?

**Comment by subesokun** [comment]
So you're saying you've a top-level project which contains several symbolic links to all of your repositories you're working on? If that is the case please have a look on #54. So far Atom doesn't support nested Git repositories.

**Comment by varemenos** [comment]
I have all my repos in a specific folder called projects (`/mnt/drivename/projects`) which I symlinked in my `~/home` directory.

Whenever I open Atom with the symlinked path for example `~/home/projects/atom-tree-view-git-status`, this package doesn't work. If I open Atom with the non-symlinked path `/mnt/drivename/projects/atom-tree-view-git-status` then it works just fine.

**Comment by tlex** [comment]
Same here, adding a symlink as project folder opens the project but doesn't display the current branch in the tree view. When adding the real path, it works.

**Comment by subesokun** [comment]
Just release v1.5.0, let me know if you've still issues 👍
