### ISSUE TITLE
Filepaths with ÅÄÖ shown as new/modified

### ISSUE THREAD

**Issue by carlhannes** [subesokun/atom-tree-view-git-status#5]
Hi!

Even if my git status says that there are no new or modified files, files with unicode characters such as Å, Ä and Ö show up as new or modified.

Example:
![Example2](http://4st.me/VzUw5.png)

Sometimes they don't show up, either, but the folder above them are marked as modified anyway.

Example:
![Example2](http://4st.me/dk0cX.png)

**Comment by subesokun** [comment]
@DeletedScreen Actually tree-view-git-status just uses the information received by the Atom [git-utils](https://github.com/atom/git-utils) package. You've to report this issue either to git-utils or [tree-view](https://github.com/atom/tree-view) (or to the atom main repo). Sorry that I can't help you more on that.

**Comment by carlhannes** [comment]
Thank you! Will do @subesokun
