### ISSUE TITLE
[Git Flow support] Master branch icon missing

### ISSUE THREAD

**Issue by radAragon** [subesokun/atom-tree-view-git-status#51]
Report: I see the gray color on my master branch (actually named "releases") but the icon is missing. The other icons on develop, feature and hotfix branches are lovely perfect.

Below is my .git configuration:

```
[gitflow "branch"]
    master = releases
    develop = develop
[gitflow "prefix"]
    feature = feature/
    bugfix = bugfix/
    release = qa
    hotfix = hotfix/
    support = support/
    versiontag =
```

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
