### ISSUE TITLE
not working when top folder does not contain .git folder

### ISSUE THREAD

**Issue by normoes** [subesokun/atom-tree-view-git-status#54]
tree-view-git-status seems not to consider a top level folder, which itself does not contain a .git folder, but contains folders that contain .git folders.

---

- Add a folder (**top level folder**), that itself does not contain a .git folder, to atom.
  - Within this folder the git repository folders are located, e.g. **git_repo**.
  -  In tree-view there is no git status information displayed for **git_repo**.
-  Add one of the git repository folders, e.g. **git_repo**, directly to atom (so it itself is top level)
  -  The information is displayed correctly, then.

- tree-view:
  - **top level folder**/
    - **git_repo**/
      - .git/
      - some_folder/
  - **git_repo**/ **[master | 4]**
      - git/
      - some_folder/

Package Version:
1.4.0

OS:
3.19.0-80-generic #88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Atom Version: 
1.17.0 x64
Atom UI Theme:
One Dark
Atom Syntax Theme:
One Dark

**Comment by nklmilojevic** [comment]
I have this issue as well.

**Comment by subesokun** [comment]
Sorry for the late reply. This is actually not an issue of this package but of Atom's implementation of the TreeView. Atom doesn't support so far nested Git repositories hence the top level project has to be a Git repository.
