### ISSUE TITLE
Commits do not update commit counters in project pane

### ISSUE THREAD

**Issue by danielb42** [subesokun/atom-tree-view-git-status#61]
When doing a commit the ahead/behind counters next to the project name are not correctly updated. Only when saving the (unchanged) file once more the numbers suddenly become correct.

This affects any version of Atom after 1.25.1. That is the last version where a commit immediately updates the counters without needing an additional UI-action. 

---

Package Version: 1.5.0

OS: Ubuntu 18.04
Atom Version: any after 1.25.1
Atom UI Theme: Atom Dark
Atom Syntax Theme: Atom Dark

**Comment by subesokun** [comment]
Is the commit counter in the bottom bar of Atom correctly working for you? If it shows something different as the tree-view shows, then it might be an issue within this package. If not you'd need to contact the Atom support.

**Comment by danielb42** [comment]
Yes, the bottom bar is still "correct-on-commit".
