### ISSUE TITLE
Takes too long to update tree view

### ISSUE THREAD

**Issue by iamsteelone** [subesokun/atom-tree-view-git-status#62]
When amending anything in the tree view, such as creating/saving/updating a file the colours do not come on until i leave the package and come back.

---

Package Version: 1.52

OS: Windows 10
Atom Version: 1.34.0
Atom UI Theme: Flatland Dark
Atom Syntax Theme: Railscast

**Comment by subesokun** [comment]
This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
