### ISSUE TITLE
Files are colored even though there are no uncommited changes

### ISSUE THREAD

**Issue by andrepintado** [subesokun/atom-tree-view-git-status#63]
I have 5 colored files on my tree view (along with it's path, their parent's path, their parent's parent's path, etc, until the name of the project) even though there are no uncommitted changes.

I played around with the `core.ignorecase` git config attribute because I wanted to change the case of these files. I managed to change them, commit and push them. It's been quite a while now, I've worked on many branches, committed them, pushed them, tried to reinstall `atom-tree-view-git-status` package, but the files are still colored. Can you help me?

![screenshot 2019-01-11 at 13 13 48](https://user-images.githubusercontent.com/6641126/51035866-53b90e00-15a3-11e9-95b5-dde152c86d8b.png)

---

Package Version: 1.5.2

OS: MacOS Mojave 10.14.2
Atom Version: 1.34.0
Atom UI Theme: One Dark
Atom Syntax Theme: One Dark

**Comment by subesokun** [comment]
> This project is no longer maintained as Atom and all repositories under Atom will be archived on December 15, 2022. Learn more in the [official announcement](https://github.blog/2022-06-08-sunsetting-atom/). Thank you for your interest in this project and your support!
