### ISSUE TITLE
All items colored as changed but are not

### ISSUE THREAD

**Issue by michaelaye** [subesokun/atom-tree-view-git-status#8]
Since the last update, all items in my project are colored in orange that supposedly indicates a git status change, but the actual git status is clean.

<img width="219" alt="screenshot 2015-08-10 12 51 57" src="https://cloud.githubusercontent.com/assets/69774/9180273/a51b520e-3f5e-11e5-8922-380b57cea51c.png">

System: Atom 1.0.5 on Mac OSX 10.10.4

**Comment by subesokun** [comment]
@michaelaye Thanks for reporting your issue! Wow that looks really strange. Could you do me a favor and check if the items are not colored in case the tree-view-git-status package is disabled? And which Theme are you using?

**Comment by michaelaye** [comment]
If I disable it, the first line `iuvs [master]` is getting uncolored. And I just realized that things work correctly for local projects, this project is on a SMB mounted remote file-sytem, maybe that has something to do with it? My themes are OneDark, both for UI and Syntax.

**Comment by subesokun** [comment]
Ok that makes me a bit nervous that you still see `iuvs [master]` in case you've disabled the package. Normally this `[master]` label should have been completely removed when deactivating it. I've not tested SMD mounted remote file-systems yet but it could be that the tree-view behaves then different. Does the `[master]` label disappears when deactivating the tree-view-git-status package in case the project root folder is a local project?

**Comment by michaelaye** [comment]
Sorry, I was imprecise, the [master] disappears both for local and remote projects.

**Comment by subesokun** [comment]
Ok, phew that are good news :) If you copy the exact same buggy remote folder onto your local file system and open it from there you can't observe the bug right?

**Comment by michaelaye** [comment]
No, I still can see the same behavior with a local copy. I just copied the remotely bound folder with "cp -R foldername ." and it looks the same. I just checked the access rights and interestingly, all group and other  access rights are denied:

``` bash
drwx------  25 klay6683  LASP\Domain Users   850B Aug 10 13:19 .
drwxr-xr-x  21 klay6683  LASP\Domain Users   714B Aug 10 13:19 ..
drwx------  20 klay6683  LASP\Domain Users   680B Aug 10 13:19 .git
-rwx------   1 klay6683  LASP\Domain Users   740B Aug 10 13:19 .gitignore
-rwx------   1 klay6683  LASP\Domain Users   591B Aug 10 13:19 .travis.yml
drwx------   7 klay6683  LASP\Domain Users   238B Aug 10 13:19 IUVS.egg-info
-rwx------   1 klay6683  LASP\Domain Users   758B Aug 10 13:19 LICENSE.md
-rwx------   1 klay6683  LASP\Domain Users   669B Aug 10 13:19 README.md
drwx------   3 klay6683  LASP\Domain Users   102B Aug 10 13:19 __pycache__
drwx------   5 klay6683  LASP\Domain Users   170B Aug 10 13:19 bin
-rwx------   1 klay6683  LASP\Domain Users   3.3K Aug 10 13:19 dark_first_data.pro
-rwx------   1 klay6683  LASP\Domain Users   2.7K Aug 10 13:19 dark_scale.pro
drwx------   3 klay6683  LASP\Domain Users   102B Aug 10 13:19 dist
-rwx------   1 klay6683  LASP\Domain Users   1.8K Aug 10 13:19 hk.py
drwx------  13 klay6683  LASP\Domain Users   442B Aug 10 13:19 iuvs
-rwx------   1 klay6683  LASP\Domain Users   3.7K Aug 10 13:19 iuvs_dn_to_temp.pro
-rwx------   1 klay6683  LASP\Domain Users   243B Aug 10 13:19 iuvs_local.sublime-project
-rwx------   1 klay6683  LASP\Domain Users    16K Aug 10 13:19 iuvs_testing.sublime-workspace
-rwx------   1 klay6683  LASP\Domain Users   243B Aug 10 13:19 iuvs_vm.sublime-project
-rwx------   1 klay6683  LASP\Domain Users    16K Aug 10 13:19 iuvs_vm.sublime-workspace
drwx------  74 klay6683  LASP\Domain Users   2.5K Aug 10 13:19 notebooks
-rwx------   1 klay6683  LASP\Domain Users    49B Aug 10 13:19 requirements.txt
-rwx------   1 klay6683  LASP\Domain Users   670B Aug 10 13:19 setup.py
-rwx------   1 klay6683  LASP\Domain Users   680B Aug 10 13:19 spice.py
drwx------   4 klay6683  LASP\Domain Users   136B Aug 10 13:19 tests
```

while for working projects `group` and `others` have read rights.

**Comment by subesokun** [comment]
I've cloned your [ivus repo](https://github.com/michaelaye/iuvs) and modified a file but so far the highlighting was correct. Could you do a `git status` and tell me which files have been modified in your case?

**Comment by subesokun** [comment]
Oh sorry you've mentioned that the git status was clean. Very strange... not sure yet how I can reproduce your issue. I've to think about how I can add some useful debug messages. The tree-view-git-status modifies only the title root element but not the file or other folder items in the tree-view. So normally it's not possible that these changes to the root title node are leaking into the other DOM nodes... but obviously something goes wrong.

**Comment by subesokun** [comment]
Hi @michaelaye, recently on some other windows machine I've observed the same issue. At first glance it looked like this was not an issue of tree-view-git-status itself, rather the `git-utils` of Atom itself reported all files as modified. Maybe Atom was not able to correctly read out the git status of each file and then ended up in marking all files as modified. When I've more informations I'll let you know.

**Comment by subesokun** [comment]
Closing this issue as it's Atom related.
